name: Deploy App

on:
  push:
    branches:
      - deploy

jobs:
  auth:
    runs-on: ubuntu-latest
    outputs:
      authenticated: ${{ steps.authenticated.outcome }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        id: authenticated
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

  deploy-backend:
    needs: auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker with GCP
        run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Build and Push Docker image
        working-directory: backend
        run: |
          IMAGE=${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/backend/backend-service:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backend-service \
            --image=${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/backend/backend-service:latest \
            --platform=managed \
            --region=${{ vars.GCP_REGION }} \
            --project=${{ vars.GCP_PROJECT_ID }} \
            --allow-unauthenticated \
            --update-secrets=STRIPE_PRIVATE_KEY=STRIPE_PRIVATE_KEY:latest \
            --update-secrets=DATABASE_URL=DATABASE_URL:latest 

  deploy-frontend:
    needs: auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install & build frontend
        working-directory: frontend
        run: |
          yarn install
          yarn build

      - name: Upload to GCS
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: frontend/dist
          destination: "${{ vars.GCP_PROJECT_ID }}-frontend"
          parent: false

  deploy-cloud-functions:
    needs: auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build function
        working-directory: cloud-functions/cancel-stripe-session
        run: yarn build

      - name: Deploy cancel-stripe-session function
        working-directory: cloud-functions/cancel-stripe-session
        run: |
          gcloud functions deploy cancel-stripe-session \
            --source=cloud-functions/cancel-stripe-session/dist \
            --runtime=nodejs22 \
            --trigger-http \
            --region=${{ vars.GCP_REGION }} \
            --entry-point=handler \
            --project=${{ vars.GCP_PROJECT_ID }} \
            --update-secrets=STRIPE_PRIVATE_KEY=STRIPE_PRIVATE_KEY:latest \
            --update-secrets=DATABASE_URL=DATABASE_URL:latest

      - name: Copy file to dist/
        working-directory: cloud-functions/cancel-stripe-session
        run: |
          cp package.json dist/
          cp yarn.lock dist/